name: "Sample React CI Pipeline / workflow"

on:
    push:
        branches:
            - main
            - master
jobs:
    build-and-test:
        runs-on: windows-latest

        steps:
           - name: "Setup Node JS"
             uses: actions/setup-node@v4 # 'uses' property: this helps us to define a github action and 'actions/setup-node@v4' this is a predefined action
             with: # 'with' property is like a variable for 'uses' property
               node-version: '22'
      
           - name: "Check node version"
             run: node --version # 'run' property is used to run linux command
           
           - name: "Clone the repository"
             uses: actions/checkout@v2
             
           - name: "List dependencies"
             run: ls
           - name: "Install dependencies"
             run: npm i
           
           - name: "List dependencies"
             run: ls             

           - name: "Run lint"
             run: npm run lint

           - name: "Run tests" # If the all test are passed the n it goes run build otherwise it fails.
             run: npm test

           - name: "Run build"
             run: npm run build
           
           - name: "Upload product-ready build files"
             uses: actions/upload-artifact@v4
             with:
              name: build
              path: dist