name: "Sample React CI Pipeline / workflow"

on:
    push:
        branches:
            - main
            - master
jobs:
    build-and-test:
        runs-on: windows-latest

        steps:
            - name: "Setup Node JS"
              uses: action/setup-node@v4
              with:
                node-version: '22'
